// main.cpp
T_("Monday")
fiFI("Maanantai")
plPL("Poniedziałek")
T_("Tuesday")
fiFI("Tiistai")
plPL("Wtorek")
T_("Wednesday")
fiFI("Keskiviikko")
plPL("Środa")
T_("Thursday")
fiFI("Torstai")
plPL("Czwartek")
T_("Friday")
fiFI("Perjantai")
plPL("Piątek")
T_("Saturday")
fiFI("Lauantai")
plPL("Sobota")
T_("Sunday")
fiFI("Sunnuntai")
plPL("Niedziela")

T_("Mo")
plPL("Pn")
T_("Tu")
plPL("Wt")
T_("We")
plPL("Śr")
T_("Th")
plPL("Cz")
T_("Fr")
plPL("Pt")
T_("Sa")
plPL("So")
T_("Su")
plPL("Nd")

T_("January")
fiFI("Tammikuu")
plPL("Styczeń")
T_("February")
fiFI("Helmikuu")
plPL("Luty")
T_("March")
fiFI("Maaliskuu")
plPL("Marzec")
T_("April")
fiFI("Huhtikuu")
plPL("Kwiecień")
T_("May")
fiFI("Toukokuu")
plPL("Maj")
T_("June")
fiFI("Kes\303\244kuu")
plPL("Czerwiec")
T_("July")
fiFI("Hein\303\244kuu")
plPL("Lipiec")
T_("August")
fiFI("Elokuu")
plPL("Sierpień")
T_("September")
fiFI("Syyskuu")
plPL("Wrzesień")
T_("October")
fiFI("Lokakuu")
plPL("Październik")
T_("November")
fiFI("Marraskuu")
plPL("Listopad")
T_("December")
fiFI("Joulukuu")
plPL("Grudzień")

T_("Week")
fiFI("Viikko")
plPL("Tydzień")
T_("Wk")
fiFI("Vko")
plPL("Ty.")

T_("Today")
fiFI("T\303\244n\303\244\303\244n")
plPL("Dziś")

T_("Next month")
fiFI("Seuraava kuukausi")
plPL("Następny miesiąc")
T_("Previous month")
fiFI("Edellinen kuukausi")
plPL("Poprzedni miesiąc")

T_("Next year")
fiFI("Seuraava vuosi")
plPL("Następny rok")
T_("Previous year")
fiFI("Edellinen vuosi")
plPL("Poprzedni rok")
