#ifndef _Vfs_Core_MetaKinds_h_
#define _Vfs_Core_MetaKinds_h_

struct VfsValueSubset;


// Don't change the order! It breaks VfsValue serialization and all user files
enum {
	METAKIND_BEGIN = 1000,
	
	#if 0
	METAKIND_DATABASE_SOURCE,
	METAKIND_PKG_ENV,
	METAKIND_CONTEXT,
	METAKIND_DB_REF,
	#endif
	
	METAKIND_COMMENT = 1005,
	
	#if 0
	METAKIND_ECS_SPACE,
	
	METAKIND_EXTENSION_BEGIN = 2000,
	
	METAKIND_ECS_ENTITY,
	
	METAKIND_ECS_COMPONENT_BEGIN = 3000,
	METAKIND_ECS_COMPONENT_UNDEFINED = METAKIND_ECS_COMPONENT_BEGIN,
	
	METAKIND_ECS_COMPONENT_PROFILE = 3100,
	METAKIND_ECS_COMPONENT_OWNER,
	METAKIND_ECS_COMPONENT_UNUSED____0,
	METAKIND_ECS_COMPONENT_SCRIPT,
	METAKIND_ECS_COMPONENT_LYRICS,
	METAKIND_ECS_COMPONENT_SONG,
	METAKIND_ECS_COMPONENT_PERSPECTIVE,
	METAKIND_ECS_COMPONENT_ARTIST,
	METAKIND_ECS_COMPONENT_NOTEPAD,
	METAKIND_ECS_COMPONENT_AUDIO_TRANSCRIPT,
	METAKIND_ECS_COMPONENT_TRANSCRIPT_PROOFREAD,
	//METAKIND_ECS_COMPONENT_PROOFREAD_STORYLINE,
	METAKIND_ECS_COMPONENT_STORYLINE_CONVERSION,
	METAKIND_ECS_COMPONENT_STORYLINE_SCRIPT,
	METAKIND_ECS_COMPONENT_SCRIPT_CONVERSION,
	METAKIND_ECS_COMPONENT_SCRIPT_SPEECH,
	//METAKIND_ECS_COMPONENT_STORYLINE_DIALOG, // TODO remove
	
	METAKIND_ECS_COMPONENT_RELEASE = 3200,
	METAKIND_ECS_COMPONENT_RELEASE_BRIEFING,
	METAKIND_ECS_COMPONENT_RELEASE_COVER_IMAGE,
	METAKIND_ECS_COMPONENT_PLATFORM_MANAGER,
	METAKIND_ECS_COMPONENT_SCRIPT_REASONING,
	METAKIND_ECS_COMPONENT_LEAD_TEMPLATE,
	METAKIND_ECS_COMPONENT_LEAD_PUBLISHER,
	METAKIND_ECS_COMPONENT_BIOGRAPHY,
	METAKIND_ECS_COMPONENT_BIOGRAPHY_PERSPECTIVES,
	METAKIND_ECS_COMPONENT_SCRIPT_TEXT,
	
	METAKIND_ECS_COMPONENT_BIOGRAPHY_ANALYSIS = 3300,
	METAKIND_ECS_COMPONENT_IMG_LAYER,
	METAKIND_ECS_COMPONENT_IMG_GEN_LAYER,
	METAKIND_ECS_COMPONENT_IMG_ASPECT_FIXER_LAYER,
	METAKIND_ECS_COMPONENT_VIDEO_PROMPT_MAKER,
	METAKIND_ECS_COMPONENT_VIDEO_STORYBOARD,
	METAKIND_ECS_COMPONENT_LEAD_DATA,
	METAKIND_ECS_COMPONENT_PROJECT_WIZARD,
	METAKIND_ECS_COMPONENT_PROVIDER,
	METAKIND_ECS_COMPONENT_VIDEO_SOURCE_FILE,
	METAKIND_ECS_COMPONENT_VIDEO_SOURCE_FILE_RANGE,
	
	METAKIND_ECS_COMPONENT_DECISION_MAKER = 3400,
	METAKIND_ECS_COMPONENT_ASSERTIONS,
	METAKIND_ECS_COMPONENT_AGGRESSIONS,
	METAKIND_ECS_COMPONENT_STRENGTH,
	METAKIND_ECS_COMPONENT_LEADERSHIP,
	METAKIND_ECS_COMPONENT_JUSTICE,
	METAKIND_ECS_COMPONENT_SENTIMENTALITY,
	METAKIND_ECS_COMPONENT_ADDICTION,
	METAKIND_ECS_COMPONENT_CARETAKER,
	
	METAKIND_ECS_COMPONENT_SUPPORT_SYSTEM = 3500,
	METAKIND_ECS_COMPONENT_BEAUTY_STANDARD,
	METAKIND_ECS_COMPONENT_ATTRACTIVENESS,
	METAKIND_ECS_COMPONENT_WILLINGNESS,
	METAKIND_ECS_COMPONENT_FACTORY,
	METAKIND_ECS_COMPONENT_PRODUCT,
	METAKIND_ECS_COMPONENT_CONSUMER,
	METAKIND_ECS_COMPONENT_COMPOSITION,
	METAKIND_ECS_COMPONENT_SONG_IDEA,
	METAKIND_ECS_COMPONENT_LITIGATION,
	METAKIND_ECS_COMPONENT_LAWYER,
	METAKIND_ECS_COMPONENT_JUDGE,
	METAKIND_ECS_COMPONENT_LOBBYING,
	// TODO fill this from macros
	
	METAKIND_ECS_COMPONENT_AI_CHAT = 3600,
	METAKIND_ECS_COMPONENT_AI_COMPLETION,
	METAKIND_ECS_COMPONENT_AI_STAGE,
	METAKIND_ECS_COMPONENT_VFS_PROGRAM,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_NODE,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_FIXED_VALUE, // unused
	METAKIND_ECS_COMPONENT_AI_STAGE_SESSION_TEMPLATE,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_QUERY,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_RESPONSE,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_COMMENT,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_EXAMPLE_VALUE,
	METAKIND_ECS_COMPONENT_AI_STAGE_PROMPT_INPUT_VALUE,
	METAKIND_ECS_COMPONENT_AI_STAGE_EXAMPLE,
	METAKIND_ECS_COMPONENT_AI_CHAIN,
	METAKIND_ECS_COMPONENT_AI_CHAIN_SESSION,
	METAKIND_ECS_COMPONENT_AI_PROGRAM,
	METAKIND_ECS_COMPONENT_AI_AGENT,
	
	METAKIND_ECS_COMPONENT_END,
	
	
	METAKIND_ECS_VIRTUAL_BEGIN = 4000,
	METAKIND_ECS_VIRTUAL_IO_SCRIPT,
	METAKIND_ECS_VIRTUAL_IO_SCRIPT_PART_PROOFREAD,
	METAKIND_ECS_VIRTUAL_IO_SCRIPT_PART_LINE,
	METAKIND_ECS_VIRTUAL_IO_SCRIPT_PART_SUB,
	
	METAKIND_ECS_VIRTUAL_VALUE_BEGIN = 4100,
	METAKIND_ECS_VIRTUAL_VALUE_SRCTEXT,
	
	
	METAKIND_EXTENSION_END = 5000,
	
	#endif
	
};

/*inline bool IsEcsComponentKind(int kind) {
	return kind > METAKIND_ECS_COMPONENT_BEGIN && kind < METAKIND_ECS_COMPONENT_END;
}*/

#if 0

// Categories (with opposites... see pairs)
// NOTE: This is kinda nonsensical placeholder at the moment.
//       This should evolve to a dynamic group/value list.
enum {
	CATEGORY_CODE,
	CATEGORY_ECS,
	
	CATEGORY_ASSET,
	CATEGORY_DISPOSABLE,
	
	CATEGORY_PRIVATE,
	CATEGORY_PUBLIC,
	
	CATEGORY_MALE,
	CATEGORY_FEMALE,
	
	CATEGORY_BUYER,
	CATEGORY_SELLER,
	
	CATEGORY_CONSUMER,
	CATEGORY_MARKETER,
	
	CATEGORY_SOUND,
	CATEGORY_TEXT,
	
	CATEGORY_PHOTO,
	CATEGORY_VIDEO,
	
	#if 0
	CATEGORY_2D,
	CATEGORY_3D,
	
	CATEGORY_STATIC,
	CATEGORY_DYNAMIC,
	#endif
	
	CATEGORY_COUNT // feel free to add
};

enum {
	CATEGORY_GROUP_PROGRAMMING,
	CATEGORY_GROUP_VALUE,
	CATEGORY_GROUP_VISIBILITY,
	CATEGORY_GROUP_GENDER,
	CATEGORY_GROUP_TRANSACTION,
	CATEGORY_GROUP_DESIRABILITY,
	CATEGORY_GROUP_AUDIO_PRODUCT,
	CATEGORY_GROUP_VISUAL_PRODUCT,
	
	CATEGORY_GROUP_COUNT
};
String GetCategoryGroupString(int i);
String GetCategoryString(int i);
Vector<String> GetCategories();
int FindCategory(const String& s);

#endif

#endif
