#include "Maestro.h"
#include "ProjectScaffolder.h"

namespace Upp {

bool ProjectScaffolder::InitMaestro(const String& dir)
{
	static const char* dirs[] = {
		"docs/maestro", "docs/maestro/tracks", "docs/maestro/phases",
		"docs/maestro/tasks", "docs/maestro/sessions", "docs/maestro/log_scans", 
		"docs/maestro/issues", "docs/maestro/playbooks", "docs/maestro/workflows",
		"docs/maestro/runbooks/items", "docs/maestro/plans/workgraphs"
	};
	
	for(const char* d : dirs) {
		RealizeDirectory(AppendFileName(dir, d));
	}
	
	String settings_path = AppendFileName(dir, "docs/Settings.md");
	if(!FileExists(settings_path)) {
		String content = "# Maestro Settings\n\n## Project Configuration\n- Project name: " + GetFileName(dir) + "\n";
		SaveFile(settings_path, content);
	}
	
	return true;
}

bool ProjectScaffolder::Scaffold(const String& dir, const String& name, const String& template_name)
{
	RealizeDirectory(dir);
	InitMaestro(dir);
	
	if(template_name == "gui" || template_name == "accounting") {
		String upp_path = AppendFileName(dir, name + ".upp");
		if(!FileExists(upp_path)) {
			String desc = (template_name == "accounting") ? "Small Accounting App generated by Maestro" : "GUI App generated by Maestro";
			String content;
			content << "description \"" << desc << "\377\";\n\n"
			        << "uses\n\tCtrlLib;\n\n"
			        << "file\n\tmain.cpp;\n\n"
			        << "mainconfig\n\t\"\" = \"GUI\";\n";
			SaveFile(upp_path, content);
		}
		
		String cpp_path = AppendFileName(dir, "main.cpp");
		if(!FileExists(cpp_path)) {
			String msg = (template_name == "accounting") ? "Small Accounting App Ready!" : "Hello Maestro!";
			String content;
			content << "#include <CtrlLib/CtrlLib.h>\n\n"
			        << "using namespace Upp;\n\n"
			        << "GUI_APP_MAIN\n"
			        << "{\n"
			        << "\tPromptOK(\"" << msg << "\");\n"
			        << "}\n";
			SaveFile(cpp_path, content);
		}
	}
	
	return true;
}

}