#include "AICore.h"


NAMESPACE_UPP


COMPONENT_STUB_IMPL(AudioTranscript, METAKIND_ECS_COMPONENT_AUDIO_TRANSCRIPT)
COMPONENT_STUB_IMPL(ScriptSpeech, METAKIND_ECS_COMPONENT_SCRIPT_SPEECH)


END_UPP_NAMESPACE
