#ifndef _ByteVM_PyCode_h_
#define _ByteVM_PyCode_h_

namespace Upp {

enum PyCode {
	PY_NOP = 0,
	PY_POP_TOP = 1,
	PY_ROT_TWO = 2,
	PY_ROT_THREE = 3,
	PY_DUP_TOP = 4,
	PY_DUP_TOP_TWO = 5,
	PY_UNARY_POSITIVE = 10,
	PY_UNARY_NEGATIVE = 11,
	PY_UNARY_NOT = 12,
	PY_UNARY_INVERT = 15,
	PY_BINARY_POWER = 19,
	PY_BINARY_MULTIPLY = 20,
	PY_BINARY_TRUE_DIVIDE = 21,
	PY_BINARY_FLOOR_DIVIDE = 22,
	PY_BINARY_MODULO = 23,
	PY_BINARY_ADD = 24,
	PY_BINARY_SUBTRACT = 25,
	PY_BINARY_SUBSCR = 26,
	PY_RETURN_VALUE = 30,
	PY_GET_ITER = 31,
	PY_FOR_ITER = 32,
	
	PY_HAVE_ARGUMENT = 90,
	
	PY_LOAD_CONST = 100,
	PY_LOAD_NAME = 101,
	PY_STORE_NAME = 102,
	PY_LOAD_GLOBAL = 103,
	PY_STORE_GLOBAL = 104,
	PY_LOAD_ATTR = 105,
	PY_STORE_ATTR = 106,
	PY_BUILD_LIST = 107,
	PY_BUILD_MAP = 108,
	PY_CALL_FUNCTION = 109,
	PY_JUMP_ABSOLUTE = 110,
	PY_POP_JUMP_IF_FALSE = 111,
	PY_JUMP_IF_FALSE_OR_POP = 112,
	PY_JUMP_IF_TRUE_OR_POP = 113,
	PY_COMPARE_OP = 114,
};

enum PyCompare {
	PY_CMP_LT,
	PY_CMP_LE,
	PY_CMP_EQ,
	PY_CMP_NE,
	PY_CMP_GT,
	PY_CMP_GE,
};

}

#endif