#ifndef _ByteVM_PyCode_h_
#define _ByteVM_PyCode_h_

NAMESPACE_UPP

enum PyOpCode {
	PY_NOP = 0,
	PY_POP_TOP = 1,
	PY_ROT_TWO = 2,
	PY_ROT_THREE = 3,
	PY_DUP_TOP = 4,
	PY_DUP_TOP_TWO = 5,
	
	PY_UNARY_POSITIVE = 10,
	PY_UNARY_NEGATIVE = 11,
	PY_UNARY_NOT = 12,
	PY_UNARY_INVERT = 15,
	
	PY_BINARY_MATRIX_MULTIPLY = 16,
	PY_INPLACE_MATRIX_MULTIPLY = 17,
	
	PY_BINARY_POWER = 19,
	PY_BINARY_MULTIPLY = 20,
	PY_BINARY_MODULO = 22,
	PY_BINARY_ADD = 23,
	PY_BINARY_SUBTRACT = 24,
	PY_BINARY_SUBSCR = 25,
	PY_BINARY_FLOOR_DIVIDE = 26,
	PY_BINARY_TRUE_DIVIDE = 27,
	
	PY_STORE_SUBSCR = 60,
	PY_DELETE_SUBSCR = 61,
	
	PY_GET_ITER = 68,
	PY_FOR_ITER = 93,
	
	PY_STORE_ATTR = 95,
	PY_LOAD_ATTR = 106,
	PY_COMPARE_OP = 107,
	PY_IMPORT_NAME = 108,
	PY_IMPORT_FROM = 109,
	PY_IMPORT_STAR = 110,
	
	PY_JUMP_FORWARD = 111,
	PY_JUMP_IF_FALSE_OR_POP = 112,
	PY_JUMP_IF_TRUE_OR_POP = 113,
	PY_JUMP_ABSOLUTE = 114,
	PY_POP_JUMP_IF_FALSE = 115,
	PY_POP_JUMP_IF_TRUE = 116,
	
	PY_LOAD_GLOBAL = 117,
	
	PY_LOAD_FAST = 124,
	PY_STORE_FAST = 125,
	
	PY_LOAD_CONST = 100,
	PY_LOAD_NAME = 101,
	PY_STORE_NAME = 90,
	PY_STORE_GLOBAL = 97,
	
	PY_CALL_FUNCTION = 131,
	PY_MAKE_FUNCTION = 132,
	PY_BUILD_LIST = 103,
	PY_BUILD_TUPLE = 102,
	PY_BUILD_MAP = 105,
	PY_BUILD_CONST_KEY_MAP = 156,
	PY_LIST_APPEND = 162,
	
	PY_RETURN_VALUE = 83
};

enum PyCompare {
	PY_CMP_LT = 0,
	PY_CMP_LE = 1,
	PY_CMP_EQ = 2,
	PY_CMP_NE = 3,
	PY_CMP_GT = 4,
	PY_CMP_GE = 5,
	PY_CMP_IN = 6,
	PY_CMP_NOT_IN = 7
};

END_UPP_NAMESPACE

#endif
