T_("Exit")
fiFI("Lopeta")
plPL("Koniec")

T_("To tray")
plPL("Schowek")

T_("Files")
fiFI("Tiedostot")
plPL("Pliki")
T_("Options")
fiFI("Asetukset")
plPL("Opcje")

T_("Open")
fiFI("Avaa")
plPL("Otwórz")
T_("Save as")
fiFI("Tallenna nimell\303\244")
plPL("Zapisz jako")
T_("Import")
fiFI("Tuo")
plPL("Importuj")
T_("Export")
fiFI("Vie")
plPL("Eksportuj")

T_("Language")
fiFI("Kieli")
plPL("Język")
T_("File associations")
plPL("Powiązania plików")
T_("Go to played file")
plPL("Idź do otwarzanego utworu")
T_("Follow played file")
plPL("Podążaj za odtwarzanym utworem")
T_("Play last file on startup")
plPL("Odtwarzaj ostatni odgrwany utwór")
T_("Go to last file on startup")
plPL("Ustawiaj się na ostatnim wskazanym utworze")
T_("Bring player to front when loading from explorer")
fiFI("Tuo soitin etualalle ladattaessa resurssienhallinnasta")
plPL("Pokaż okno aplikacji przy ładowaniu plików z exploratora")

T_("Register at startup")
plPL("Rejestruj przy starcie")

T_("Add files")
fiFI("Lis\303\244\303\244 tiedostoja")
plPL("Dodaj pliki")
T_("Add folder")
fiFI("Lis\303\244\303\244 kansio")
plPL("Dodaj katalog")
T_("Insert files")
plPL("Wstaw pliki")
T_("Insert folder")
plPL("Wstaw katalog")

T_("Add playlist")
fiFI("Lis\303\244\303\244 soittolista")
plPL("Dodaj listę utworów")
T_("Add folder as playlist")
fiFI("Lis\303\244\303\244 kansio soittolistana")
plPL("Dodaj katalog jako listę utworów")
T_("Insert playlist")
plPL("Wstaw listę utworów")
T_("Insert folder as playlist")
plPL("Wstaw katalog jako listę utworów")

T_("Change playlist name")
fiFI("Vaihda soittolistan nime\303\244")
plPL("Zmień nazwę listy")


T_("Position")
fiFI("Sijainti")
plPL("Pozycja")
T_("Volume")
fiFI("\303\204\303\244nenvoimakkuus")
plPL("Głośność")

T_("Playlists")
plPL("Listy utworów")

T_("Title")
fiFI("Otsikko")
plPL("Tytuł")
T_("Artist")
fiFI("Artisti")
plPL("Wykonawca")
T_("Album")
fiFI("Albumi")
plPL("Album")
T_("Length")
fiFI("Pituus")
plPL("Długość")

T_("Bring player on top when loading stream from explorer")
fiFI("Tuo soitin etualalle ladattaessa suoratoistoa resurssienhallinnasta")
plPL("Przenieś okno odtwarzacza na wierzch przy ładowaniu strumienia z explorera")

T_("Load")
fiFI("Lataa")
plPL("Załaduj")

T_("File %s does not exists")
plPL("Plik %s nie istnieje")

T_("Cancel")
fiFI("Peruuta")
plPL("Anuluj")

T_("Select music folder")
plPL("Wybierz katalog z muzyką")
T_("Select music file")
plPL("Wybierz plik")

T_("Playing..")
plPL("Odtwarzanie..")
T_("Playing paused")
plPL("Odtawrzanie wstrzymane")

T_("Pause")
fiFI("Tauko")
plPL("Wstrzymaj")
T_("Play")
fiFI("Toista")
plPL("Odtwarzaj")

T_("Next song")
plPL("Następny utwór")
T_("Previous song")
plPL("Poprzedni utwór")
T_("Order mode")
plPL("Kolejność odtwarzania")
T_("Repeat mode")
plPL("Tryb powtarzania")
T_("Exit player")
plPL("Wyjdź z programu")
T_("Hide player to tray")
plPL("Ukryj do schowka")
T_("Play/Pause")
plPL("Odtwarzaj/Wstrzymaj")
T_("Stop")
fiFI("Pys\303\244yt\303\244")
plPL("Zatrzymaj")
