#ifndef _AICore2_Enum_h_
#define _AICore2_Enum_h_

typedef enum {
	SEARCHSTRATEGY_NULL = -1,
	SEARCHSTRATEGY_MINIMAX,
	SEARCHSTRATEGY_ALPHA_BETA,
	SEARCHSTRATEGY_BREADTH_FIRST,
	SEARCHSTRATEGY_UNIFORM_COST,
	SEARCHSTRATEGY_DEPTH_FIRST,
	SEARCHSTRATEGY_DEPTH_LIMITED,
	SEARCHSTRATEGY_BEST_FIRST,
	SEARCHSTRATEGY_ASTAR,
	
	SEARCHSTRATEGY_COUNT,
} SearchStrategyType;

typedef enum {
	HEURISTICS_NULL = -1,
	HEURISTICS_HAMMING_DISTANCE_OF_PREDICATES,
	
	HEURISTICS_COUNT,
} HeuristicsType;

typedef enum {
	GENERATOR_NULL = -1,
	GENERATOR_RANDOM,
	GENERATOR_CUSTOM,
	
	GENERATOR_COUNT,
} GeneratorType;

#endif
