#ifndef _AICore2_Enum_h_
#define _AICore2_Enum_h_

typedef enum {
	SEARCHSTRATEGY_NULL = -1,
	SEARCHSTRATEGY_MINIMAX,
	SEARCHSTRATEGY_ALPHA_BETA,
	SEARCHSTRATEGY_BREADTH_FIRST,
	SEARCHSTRATEGY_UNIFORM_COST,
	SEARCHSTRATEGY_DEPTH_FIRST,
	SEARCHSTRATEGY_DEPTH_LIMITED,
	SEARCHSTRATEGY_BEST_FIRST,
	SEARCHSTRATEGY_ASTAR,
	
	SEARCHSTRATEGY_CUSTOM,
	SEARCHSTRATEGY_COUNT,
} SearchStrategyType;

typedef enum {
	HEURISTIC_NULL = -1,
	HEURISTIC_SIMPLE,
	HEURISTIC_HAMMING_DISTANCE_OF_PREDICATES,
	HEURISTIC_ACTION_PLANNER,
	
	HEURISTIC_CUSTOM,
	HEURISTIC_COUNT,
} HeuristicType;

typedef enum {
	GENERATOR_NULL = -1,
	GENERATOR_RANDOM,
	GENERATOR_ACTION_PLANNER,
	
	GENERATOR_CUSTOM,
	GENERATOR_COUNT,
} GeneratorType;

typedef enum {
	TERMTEST_NULL = -1,
	TERMTEST_NO_SUB,
	TERMTEST_ACTION_PLANNER,
	
	TERMTEST_CUSTOM,
	TERMTEST_COUNT,
} TerminalTestType;

#endif
