#ifndef _ByteVM_EcmaScript_JsCode_h_
#define _ByteVM_EcmaScript_JsCode_h_

#include "EcmaScript.h"

NAMESPACE_UPP

enum JsOpCode {
	JS_NOP = 0,
	JS_POP_TOP = 1,
	JS_DUP_TOP = 4,
	
	JS_UNARY_POSITIVE = 10,
	JS_UNARY_NEGATIVE = 11,
	JS_UNARY_NOT = 12,
	
	JS_BINARY_POWER = 19,
	JS_BINARY_MULTIPLY = 20,
	JS_BINARY_MODULO = 22,
	JS_BINARY_ADD = 23,
	JS_BINARY_SUBTRACT = 24,
	JS_BINARY_SUBSCR = 25,
	
	JS_STORE_SUBSCR = 60,
	JS_DELETE_SUBSCR = 61,
	
	JS_STORE_ATTR = 95,
	JS_LOAD_ATTR = 106,
	JS_COMPARE_OP = 107,
	
	JS_JUMP_FORWARD = 111,
	JS_JUMP_ABSOLUTE = 114,
	JS_POP_JUMP_IF_FALSE = 115,
	JS_POP_JUMP_IF_TRUE = 116,
	
	JS_LOAD_GLOBAL = 117,
	JS_LOAD_FAST = 124,
	JS_STORE_FAST = 125,
	
	JS_LOAD_CONST = 100,
	JS_LOAD_NAME = 101,
	JS_STORE_NAME = 90,
	
	JS_CALL_FUNCTION = 131,
	JS_MAKE_FUNCTION = 132,
	JS_BUILD_LIST = 103,
	JS_BUILD_MAP = 105,

	JS_RETURN_VALUE = 83,

	// JS specific
	JS_TYPEOF = 150,
	JS_INSTANCEOF = 151,
	JS_DELETE = 152,
	JS_VOID = 153,
	
	// Exception handling
	JS_SETUP_EXCEPT  = 202,
	JS_POP_EXCEPT    = 203,
	JS_RAISE         = 204,
};

END_UPP_NAMESPACE

#endif
